sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION='>=1.8,<1.9'
  - DJANGO_VERSION='>=1.9,<1.11'
  - DJANGO_VERSION='>=1.11,<1.12'
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION='>=1.9,<1.11'
    - python: "3.6"
      env: DJANGO_VERSION='>=1.8,<1.9'
install:
  - "pip install Django$DJANGO_VERSION"
  - "pip install -r tests_requirements.txt"
  - "python setup.py install"
  - "pip install coveralls"
script: 
  - "coverage run --source=popolo runtests.py"
after_script:
  - coveralls --verbose
