language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION='>=1.8,<1.9'
  - DJANGO_VERSION='>=1.6,<1.7'
install:
  - "pip install Django$DJANGO_VERSION"
  - "pip install -r tests_requirements.txt"
  - "python setup.py install"
  - "pip install coveralls"
script: 
  - "coverage run --source=popolo runtests.py"
after_success:
  - coverage report -m
  - coveralls
